version: '3.8'
services:
  ome.api:
    image: ${CI_REGISTRY_IMAGE:-ome.api}:${CI_COMMIT_SHA:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};SslMode=VerifyCA;SslCa=${DB_SSL_CA_PATH}
      - Keycloak__BaseUrl=${KEYCLOAK_BASE_URL}
      - Keycloak__Realm=${KEYCLOAK_REALM}
      - Keycloak__ClientId=${KEYCLOAK_CLIENT_ID}
      - Keycloak__ClientSecret=${KEYCLOAK_CLIENT_SECRET}
      - Keycloak__AdminClientId=${KEYCLOAK_ADMIN_CLIENT_ID}
      - Keycloak__AdminClientSecret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
      - Frontend__BaseUrl=${FRONTEND_BASE_URL}
    expose:
      - 8080
    volumes:
      - /etc/ssl/certs/Coolify_Internal_CA_Root_CA_63765285545590635409030008279072883721.pem:/etc/ssl/certs/Coolify_Internal_CA_Root_CA_63765285545590635409030008279072883721.pem:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s