version: '3.8'
services:
  ome.api:
    image: ${CI_REGISTRY_IMAGE:-ome.api}:${CI_COMMIT_SHA:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ConnectionStrings__PostgresConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};SSL Mode=VerifyFull;Root Certificate=/etc/ssl/certs/coolify-ca.crt
      - Keycloak__BaseUrl=${KEYCLOAK_BASE_URL}
      - Keycloak__Realm=${KEYCLOAK_REALM}
      - Keycloak__ClientId=${KEYCLOAK_CLIENT_ID}
      - Keycloak__ClientSecret=${KEYCLOAK_CLIENT_SECRET}
      - Keycloak__AdminClientId=${KEYCLOAK_ADMIN_CLIENT_ID}
      - Keycloak__AdminClientSecret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
      - Frontend__BaseUrl=${FRONTEND_BASE_URL}
    ports:
      - "8080"
      - "8443"
    volumes:
      - /data/coolify/databases/nwkgcw0gs0k0oko0cww44gw0/ssl/server.crt:/etc/ssl/certs/coolify-ca.crt:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s